site_name: InstaVuPlugin
site_url: https://instavu3d.com/
repo_url: https://github.com/hirenreshamwala/instavu-plugin-docs.git
site_description: Web based 3d product rendering
copyright: <a href="https://instavu3d.com/">instavu3d.com</a>
theme: readthedocs
extra_css:
  - css/extra.css
markdown_extensions:
  - toc:
      permalink: True
pages:
  - Home: index.md
